# -*- coding: utf-8 -*-
"""Bank customer churn model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cn_1kfbG3FaNKCMeYYiyRmbXqaC3YDZ-
"""



"""Title Of the Project:

**Bank Customer Churn Model**

**Objective**- The objective of a bank churn model in Python is to predict and reduce customer churn. Utilizing machine learning techniques, the model aims to identify patterns and factors contributing to customer attrition, enabling proactive measures such as personalized retention strategies, enhancing customer satisfaction, and ultimately improving the bank's customer retention rates.

**Data Source **- YBI Foundation
"""

# importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importing data
df=pd.read_csv('/content/Customer-Churn-Records.csv')
df

# EDL(Exploratory Data Analysis)

df.describe()

df.size

df.info()

df.describe(include='object')

df.describe()

df.isnull().sum()

for col in df.describe():
  print(col)
  print(df[col].unique())
  print('-'*50)

for a in df.describe(include='object'):
  print(a)
  print(df[a].unique())
  print('-'*55)

# Data Visualization

plt.figure(figsize=(30,24))
df.plot.box()
plt.xticks(rotation=45)

df.corr()

plt.figure(figsize=(20,14))
sns.heatmap(df.corr(),annot=True,cmap='coolwarm')

df['Exited'].nunique()

df.hist(figsize=(14,8))
plt.show()

a=df['Exited'].value_counts()
a

a=sns.countplot(data=df,x='Gender')
plt.title('count of customers by gender')
for label in a.containers:
  a.bar_label(label)
plt.show()

y=sns.countplot(data=df,x='Geography')
plt.title('count of customers country wise')
plt.xlabel('countries')
for label in y.containers:
  y.bar_label(label)
plt.show()

z=sns.countplot(data=df,x='Card Type')
plt.title('customers having card')
for label in z.containers:
  z.bar_label(label)
plt.show()

x=sns.countplot(data=df,x='HasCrCard')
plt.title('count of customers having credit card or not')
for i in x.containers:
  x.bar_label(i)
plt.show()

y=sns.countplot(data=df,x='Exited')
plt.title('count of customers by churn status')
for i in y.containers:
  y.bar_label(i)
plt.show()

y=sns.countplot(data=df,x='IsActiveMember')
plt.title('count of customers by activity status')
for i in y.containers:
  y.bar_label(i)
plt.show()

y=sns.countplot(data=df,x='Complain')
plt.title('count of customers by Complaint status')
for i in y.containers:
  y.bar_label(i)
plt.show()

pd.plotting.parallel_coordinates(df.describe(),'Exited',color='br')
plt.xticks(rotation=45)

avg_balance_churned = df[df['Exited'] == 1]['Balance'].mean()
avg_balance_retained = df[df['Exited'] == 0]['Balance'].mean()
print('Average Balance - Churned:', avg_balance_churned)
print('Average Balance - Retained:', avg_balance_retained)

churned_customers = df.query('Exited == 1')
churned_customers
nonchurned_customers=df.query('Exited==0')
nonchurned_customers

x=sns.countplot(data=churned_customers,x='Gender')
plt.title('churned customers by gender')
for i in x.containers:
  x.bar_label(i)
plt.show(x)
y=sns.countplot(data=nonchurned_customers,x='Gender')
plt.title('Non churned customers by gender')
for i in y.containers:
  y.bar_label(i)
plt.show(y)

x=sns.countplot(data=churned_customers,x='Geography')
plt.title('churned customers country wise')
for i in x.containers:
  x.bar_label(i)
plt.show(x)
y=sns.countplot(data=nonchurned_customers,x='Geography')
plt.title('non churned customers country wise')
for i in y.containers:
  y.bar_label(i)
plt.show(y)

credit_card=df.query('HasCrCard==1')
credit_card
no_credit_card=df.query('HasCrCard==0')
no_credit_card

x=sns.countplot(data=churned_customers,x='HasCrCard')
plt.title('churned customers by credit card')
for i in x.containers:
  x.bar_label(i)
plt.show()
y=sns.countplot(data=nonchurned_customers,x='HasCrCard')
plt.title('non churned customers by credit card')
for i in y.containers:
  y.bar_label(i)
plt.show()

# importing ML libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Train-Test Split
# Define Target Variable (y) and Feature Variables (X)

x=df.drop(['Exited','Surname','Geography','Gender','Card Type','Age','EstimatedSalary','Complain','Satisfaction Score','Card Type','Point Earned'],axis=1)
y=df['Exited']
x_test,y_test,x_train,y_train=train_test_split(x,y,test_size=0.25,random_state=42)
x_test,y_test,x_train,y_train

print(df.dtypes)

x_train=x_train.to_numpy()
x_train=x_train.reshape(-1,1)

# Modeling
model=LogisticRegression()
model.fit(x_train[:2500],y_train)

# Prediction

prediction=model.predict(x_test)
print(prediction)

accuracy=accuracy_score(prediction.y_test)
print(accuracy)

percentage=f'{accuracy:.0%}'
percentage

"""Recommendations for the Bank:

Improve Customer Satisfaction: Conduct regular customer satisfaction surveys to identify pain points and areas for improvement. Addressing customer concerns promptly and effectively can help reduce churn rates.

Enhance Customer Retention Programs: Develop loyalty programs, personalized offers, and rewards to incentivize customers to stay with the bank. Building strong relationships and providing value-added services can increase customer loyalty.

Focus on Retaining Female Customers: Analyze the reasons behind the higher churn rate among female customers. Tailor marketing and customer service strategies to meet their specific needs and preferences.

Strengthen Communication Channels: Ensure effective communication channels are in place to keep customers informed about new products, services, and updates. Regularly engage with customers through personalized interactions and provide timely support.

Offer Targeted Financial Solutions: Analyze the needs and preferences of customers within the age group of 45-70. Provide tailored financial solutions, such as retirement planning, investment options, and specialized services, to meet their unique requirements.

Targeted Marketing: Leverage the insights about customer segments with higher salaries to tailor marketing strategies and offerings specifically for this group. This can strengthen relationships, increase loyalty, and reduce the likelihood of customer churn.

Provide Value-added Products and Services: Continuously assess the market to identify emerging trends and offer innovative products and services that differentiate the bank from competitors. Regularly review and update existing offerings to remain competitive.

Foster Trust and Transparency: Build trust and transparency through clear communication, fair pricing, and reliable services. Ensure customers feel valued and have confidence in the bank's integrity and commitment to their financial well-being.

Complaint Resolution: Improve the complaint resolution process by actively addressing customer complaints, providing prompt and satisfactory solutions, and enhancing customer support channels. This can help reduce churn rates associated with unresolved complaints.

Focus on Customer Education: Offer financial literacy programs and educational resources to empower customers to make informed decisions. Educated customers are more likely to remain loyal and satisfied with the bank's services.

By implementing these recommendations, the bank can strengthen customer relationships, increase customer satisfaction, and ultimately reduce churn rates. Regular monitoring and analysis of customer behavior and feedback will help refine strategies and further improve customer retention efforts.
"""